apiVersion: v1
kind: Service
metadata:
  name: demo-application
  namespace: default
spec:
  ports:
  - name: default-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-application
    env: dev
  sessionAffinity: None
  type: LoadBalancer